/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DiamondTracking {
  export type SenderStruct = { from: AddressLike; location: string };

  export type SenderStructOutput = [from: string, location: string] & {
    from: string;
    location: string;
  };
}

export interface DiamondTrackingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allDiamonds"
      | "setSenderValues"
      | "setValues"
      | "showSender"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allDiamonds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSenderValues",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setValues",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "showSender",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allDiamonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSenderValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setValues", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showSender", data: BytesLike): Result;
}

export interface DiamondTracking extends BaseContract {
  connect(runner?: ContractRunner | null): DiamondTracking;
  waitForDeployment(): Promise<this>;

  interface: DiamondTrackingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allDiamonds: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint, bigint] & { id: string; size: bigint; weight: bigint }],
    "view"
  >;

  setSenderValues: TypedContractMethod<
    [_location: string],
    [void],
    "nonpayable"
  >;

  setValues: TypedContractMethod<
    [_size: BigNumberish, _id: string, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  showSender: TypedContractMethod<
    [],
    [DiamondTracking.SenderStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allDiamonds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint, bigint] & { id: string; size: bigint; weight: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setSenderValues"
  ): TypedContractMethod<[_location: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValues"
  ): TypedContractMethod<
    [_size: BigNumberish, _id: string, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "showSender"
  ): TypedContractMethod<[], [DiamondTracking.SenderStructOutput], "view">;

  filters: {};
}
